language: cpp

compiler:
  - gcc 
  - clang
  
notifications:
  recipients:
    # - stan-buildbot@googlegroups.com
  email:
    on_success: change
    on_failure: always

script:
  - cd rstan && make build BUILD_OPTS=--no-build-vignettes && make install && make check && cd tests && R -q -f runRunitTests.R
